### ISSUE TITLE
Depends on lodash but not included in package.json

### ISSUE THREAD

**Issue by vesse** [jamonkko/console-log-server#2]
`cli.js` depends on `lodash/fp`, but it's not listed in `dependencies`.

**Comment by jarkkohon** [comment]
Thanks for the report! Will try to fix this week.

**Comment by jamonkko** [comment]
Fixed in 0.1.6

(reason I did not see this problem before was that newer npm >2 with node > 6 uses flat node_modules and one of the other deps listed lodash. But with older npm that uses tree structured node_modules the missing lodash was caught!
